# PHP CircleCI 2.0 configuration file

version: 2
jobs:
  test:
    docker:
      - image: circleci/php:8.0.3-apache
        name: Set up PHP
        environment:
           XDEBUG_MODE: coverage
      - image: circleci/mysql:8.0.20-ram
        name: Set up MySQL
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          WITH_XDEBUG: 1
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_USER: root
          MYSQL_DATABASE: dmore_testing
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''

    steps:
      - checkout
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql
            sudo apt-get install -y libzip-dev
            sudo apt-get update && sudo apt-get install -y \
                 libfreetype6-dev \
                 libjpeg62-turbo-dev \
                 libpng-dev \
                 && sudo docker-php-ext-configure gd --with-freetype --with-jpeg \
                 && sudo docker-php-ext-install -j$(nproc) gd

      - restore_cache:
          keys:
          - composer-v1-{{ checksum "composer.lock" }}
          - composer-v1-
      - run: composer install -n --prefer-dist
      - run: composer require --dev php-coveralls/php-coveralls
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # prepare the database
      - run: cp .env.ci .env
      - run: cp .env.ci .env.testing
      - run: touch storage/dmore_testing.sqlite
      - run: php artisan migrate --env=testing --database=mysql --force

      # run tests with phpunit
      # - run: php artisan test --coverage-html tests/coverage
      - run:
          command: composer run test:coverage
      - run: ./vendor/bin/php-coveralls -v

      - store_test_results:
          path: tests/coverage
      - store_artifacts:
          path: tests/coverage

workflows:
  version: 2
  workflow:
    jobs:
    - test
